### ISSUE TITLE
New account creation issues

### ISSUE THREAD

**Issue by jonathan-chin** [ByunLab/staRt-ionic#217]
Simulating on iPad air -- no option to create a new account? ~~I can only sign into existing accounts, which makes it difficult for me to test new account creation~~ "Sign in with email" is misleading and makes it seem like I already need an account.

Also, is there a way to delete old accounts? If I need to debug the new account process, I want to be able to reuse my old email addresses.

**Comment by jonathan-chin** [comment]
Additionally, I should get access to the Firebase and backend database, so I can debug better / faster.

**Comment by starakaj** [comment]
Hey, sorry for the slow response, been traveling/sick. Agreed, the whole "sign in with email" thing is misleading. I think we'd need to do some research there to figure out the best way to fix that, since that UI is 100% google. Maybe there's a way to configure it so that it can be less confusing—maybe it could read "sign in or create a new account" or something. If not, we'd have to either hack their UI or supply our own.

As far as getting you on the Firebase backend, I just added you, so you should get an invitation in your inbox.

**Comment by jonathan-chin** [comment]
@starakaj maybe the UI issue can get fixed in the RN, not the Ionic version.

Firebase backend is good. Any other database backend that we use?

Going to close the issue for now.
