### ISSUE TITLE
Word Quest LPC Displays Only Words (Inconsistently)

### ISSUE THREAD

**Issue by awanderingorill** [ByunLab/staRt-ionic#224]
When loading Word Quest, only LPC wave displays, not words

**Comment by jonathan-chin** [comment]
Was this submitted by a client? I need some more details to help reproduce the error.

Is the user on the TestFlight version?
What /r/ categories are selected?
Session trial goal?
wave hidden?

does this error happen consistently? did it only happen once or twice?

**Comment by cmsava1897** [comment]
Hi Jon,

I think this was an error that Tara noticed. The error was that Word Quest would occasionally load with the LPC but no words. Since, it was reported to be an inconsistent error, I attempted to reproduce the error 20 times. To try and reproduce the error, I entered Word Quest, selected the preferred settings, clicked through "good"/"great"/"try again" a few times, and then exited with "Stop practice". After about 13-15 attempts, the word quest screen appeared to load more slowly and at around 17 attempts, I experienced this bug. The screenshots below give information on the preferences I had selected (and my profile information). I'll also have Tara confirm that this was what she experienced. 

Reproduction #1 Settings:
![image](https://user-images.githubusercontent.com/29290645/41747629-9f1955d4-757c-11e8-98de-d6944d3f48d4.png)

Reproduction #1:
![image](https://user-images.githubusercontent.com/29290645/41747637-a429e246-757c-11e8-9d20-1a4d0779e6be.png)

Reproduction #2 Settings: 
![image](https://user-images.githubusercontent.com/29290645/41747642-ac07dffe-757c-11e8-84e7-d74a8f7e6f51.png)

Reproduction #2: 
![image](https://user-images.githubusercontent.com/29290645/41747652-b6f559f0-757c-11e8-84f6-56cb73807934.png)

Profile Settings: 
![image](https://user-images.githubusercontent.com/29290645/41747657-bc14f0c6-757c-11e8-9852-d85dd63e5307.png)

Let me know if you have any further questions! 

Christian
