### ISSUE TITLE
Profile saving race condition

### ISSUE THREAD

**Issue by jonathan-chin** [ByunLab/staRt-ionic#231]
This came up when implementing the visual reinforcement high score feature.

I created a separate notification workflow to save the new high scores to the firebase profile. Effectively, it fires a 'update-highscores' event, modeled after 'recording-complete'.

I've observed it live: Firestore briefly adds the new high scores but another trigger in the client then overwrites it and deletes it. the new function is clean and simple:

```
function _updateHighscores(msg, highscores) {
  ProfileService.getCurrentProfile().then(function (profile) {
    if (profile) {
      var changelist = []; // not sure what this is
       _incrementProfileStat(profile, 'highscores', highscores, changelist);
       _updateProfileStat(profile, 'highscores', highscores, changelist);
      ProfileService.saveProfile(profile);
       _notifyChanges(profile, currentProfileStats, changelist);
    }
  });
}
```

Race condition was an issue before and we applied a hotfix for it. The issue stems from the way profiles are saved: the entire record is overwritten, which causes the new data to be deleted.

**Comment by starakaj** [comment]
Okay, seems like we need to do a slightly better job of handling simultaneous writes, but that firebase provides some good tools for doing this. See https://firebase.google.com/docs/database/web/read-and-write#update_specific_fields

**Comment by starakaj** [comment]
Getting started on this

**Comment by starakaj** [comment]
Alright, so the solution is to use a transaction, rather than resetting the FB doc, in order to handle updates. I've added a new function to `profile-service-module.js` called `runTransactionForCurrentProfile` that's a convenience wrapper around retrieving a transaction handle. The new`_updateHighscores` function would look like this:

```
function _updateHighscores(msg, highscores) {
  ProfileService.runTransactionForCurrentProfile(function(handle, doc, t) {
    const changes = {};
    _updateProfileStat('highscores', highscores, changes);
    return changes;
  }).then(function(changes) {
    ProfileService.getCurrentProfile().then(function(profile) {
      _notifyChanges(profile, currentProfileStats, changes);
    });
  });
}
```

No need to call `_incrementProfileStat` --- that's only for then you've got a stat you want to increment, for which you need to pull and existing value first (I'm assuming highscores is some kind of object). 

Let me know if you have any questions!

**Comment by starakaj** [comment]
Been open for a long long time, assuming this has been taken care of.
