### ISSUE TITLE
Free play prompt in tutorial pops up too soon

### ISSUE THREAD

**Issue by erinmdoty** [ByunLab/staRt-ionic#288]
During the tutorial, the prompt to navigate to free play should come up on the last page of the tutorial (I think). Instead, it pops up on the second to last page, before the user has actually finished the tutorial. Note that this only happens the first time that the tutorial is viewed in a given profile.

![img_0046](https://user-images.githubusercontent.com/42744629/48285259-06e47a00-e430-11e8-9dd5-e18d17c0eea2.PNG)

Running version 1.0.30 of staRt on iPad 4th generation (AI1458) with iOS 10.3.3

**Comment by helencarey** [comment]
Hey Sam,
We added a slide to the tutorial deck in the last update. Tutorial ‘section
5: /r/sounds’ now has 6 slides.

-h

iPhone


On Nov 14, 2018, at 12:28, Sam Tarakajian <notifications@github.com> wrote:

Can reproduce. Investigating.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ByunLab_staRt-2Dionic_issues_288-23issuecomment-2D438747737&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=sdQYtDY9zFum7HlWmzDgZXYAbaQWQaump3RLYExAJqg&m=nEEVfFJRbDgDiJf2o5PgTgrTXXTpe4iIdTW1jep9VPg&s=GUn1IZ7TByydGxEvDSNdMsYQcGaSaGR9MIELV6azo6c&e=>,
or mute the thread
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AIQAwHsNCURQbcKdMSURDbUWxOMsdneyks5uvFLPgaJpZM4YXbM0&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=sdQYtDY9zFum7HlWmzDgZXYAbaQWQaump3RLYExAJqg&m=nEEVfFJRbDgDiJf2o5PgTgrTXXTpe4iIdTW1jep9VPg&s=NytMHiDsleogz5fCnr1i6idhMZ0p8dfr1fWx4K39znk&e=>
.

**Comment by starakaj** [comment]
mmmmmm

**Comment by starakaj** [comment]
Okay, I see the issue. So the problem is that you get the "Section 5 completed" coin _before_ section 5 is really completed. I think I see how to fix this...

**Comment by starakaj** [comment]
Testable in v1.0.31
