### ISSUE TITLE
Disable left nav during Quest, Quiz, and FP formal session.

### ISSUE THREAD

**Issue by helencarey** [ByunLab/staRt-ionic#345]
TM: And one more, a usability request from a formal pilot tester: she has had multiple issues where the child accidentally presses a button and the app automatically moves out of Quest mode and she has to begin again. Given the antsy nature of the target population, I imagine others will have this issue. Maybe we could hide the navigation bar while a Quest (or Quiz or Free Play) is in session? Or just use a pop-up to check if they really want to navigate away?

This becomes less of an issue once we roll out version 2.0.5 (tester is using 2.0.4), which has mid-session saving as an option. Still, it might be nice to put this on the list of usability features to consider adding down the road.

**Comment by WillHaack** [comment]
as per our meeting, bump on this. I think the best solution is a notification box "Are you sure you want to leave this session?"

**Comment by WillHaack** [comment]
Test that we properly prompt the user before they navigate away from an inprogress quest or quiz. The key idea is that you should always be prompted before navigating away from a page where the user is being recorded/graded, and you should be prompted otherwise. 

Prompt:
![image](https://user-images.githubusercontent.com/766792/65457203-091db000-de19-11e9-8937-aa8f9fbcad16.png)

- [ ] Start a Syllable Quest and try to navigate away by clicking on the leftnavbar. Make sure you see the prompt.

- [ ] Repeat above for Word Quest

- [ ] Repeat for Syllable Quiz

- [ ] Repeat for Long Word Quiz

- [ ] Repeat for Short Word Quiz

- [ ] Navigate away from a Free Play Session. You should NOT be asked to confirm to leave.

- [ ] Navigate away from the Quest page where you choose between Syllable/Word Quest. You should NOT be asked to confirm to leave.

- [ ] Navigate away from the Select /r/ Categories for a Syllable Quest. You should NOT be asked to confirm to leave.

- [ ] Navigate away from the Select /r/ Categories for a Word Quest. You should NOT be asked to confirm to leave.

- [ ] Navigate away from the Choose Quiz Type page. You should NOT be asked to confirm to leave.

**Comment by Tjc10** [comment]
Created a "Test_QuitSession" profile and tested all scenarios outlined above.  All features appeared as it should.  NO errors noted when navigating away. Nothing to note here.  Thanks!
