### ISSUE TITLE
Uploads from Profile->Recordings use a non-unique session-id

### ISSUE THREAD

**Issue by WillHaack** [ByunLab/staRt-ionic#364]
Users who do a recording session in quest or quiz, and then click "Later" when prompted to upload, are never able to upload their recording session data to the staRt server.

Unless this is their first upload for a participant, their uploads are incorrectly marked as already "Uploaded," and uploading them again does nothing.

Fixed with this patch https://github.com/ByunLab/staRt-ionic/commit/075ca64b8881fdf1ff4ca435fe0b1a6ac234e52d

**Comment by WillHaack** [comment]
QA Note:

Ensure that uploads are working properly with various flows. For all the following upload flows, make sure that a new unique row appears on https://byunlab.com/start/. 

- [ ] Create a new participant and upload their first audio file by doing a short quiz, and clicking "Okay" on Upload prompt. Then do the same for quest.

- [ ] Create a new participant and upload their first audio file by doing a short quiz, and then clicking "Later" on upload prompt, and then going to Profiles->recordings and hitting upload there. Do the same for quest.

- [ ] Repeat the following two flows on a participant that already has at least one audio file uploaded.

**Comment by Tjc10** [comment]
Hi all in regards to this ticket, I tested three different user profiles as follows:
- TwyTest_upload now: for this one, long quiz/syllable quiz/quest was completed.  All attempts to upload "now" failed.  Attempts to go into the profile/recordings section and do uploads after also resulted in upload error message.  Nne of the upload attempts came up as successful.

- TwyTest_upload now2: for this one, short quiz/syllable quiz/quest was completed.  All attempts to upload "now" failed.  Attempts to go into the profile/recordings section and do uploads after also resulted in upload error message.  None of the upload attempts came up as successful.  
***Also note that when I was prompted to do free play after completing the tutorial/quizes (these were the usual prompts), I did not receive a prompt after 5 minutes of free play.  I was actually in free play for about 8 minutes --- no prompts were ever received and I just exited and went on to do the quest.***

- TwyTest_upload later: for this one, I did short quiz/long quiz (forced to do long quiz after short because a prompt for long popped up)/syllable quiz/quest was completed.  All attempts to upload "later" failed.  Attempts to go into the profile/recordings section and do uploads after also resulted in upload error message.  None of the upload attempts came up as successful.

**Comment by WillHaack** [comment]
Thank you @Tjc10 I'll look into this and then push up a new build.

**Comment by WillHaack** [comment]
@Tjc10 I didn't include the credentials file in the build, so all uploads in every possible scenario should not work for you - which appears to be the behavior you received.

**Comment by Tjc10** [comment]
@WillHaack I was just working through my pending tasks and noticed I was tagged on this ticket.  If you would like for me to try another set of test scenarios.  Please let me know.  Did I atleast give good feeback on the behaviors you were trying to troubleshoot?  Did I miss anything?

**Comment by WillHaack** [comment]
@Tjc10 

Yes thank you! The problem that I realized from your comments was that I made a mistake unrelated to the bug you were testing that made it so that ALL uploads didn't work. So when I push up the new version, i'll need you to do these tasks again. Sorry about that!

**Comment by WillHaack** [comment]
V2.0.11 is out, so you can go ahead and try this flow again when you get the time.

**Comment by Tjc10** [comment]
Hi all, I created profiles and tested as outlined above under the QA Note.  All upload attempts were successful this time around.  For reference, I created two profiles: "TwyTest2.0.11 OKAY" and "TwyTest2.0.11 LATER" - upload was successful under all test conditions.
I also tested a previously created profile "QACheckpoints TCTesting" and did a short quiz OKAY plus a quest OKAY (both times I selected upload now).  Upload now was successful both times.  I used the same previously created profile "QACheckpoints TCTesting" and did a short quiz LATER plus a quest LATER (both times I selected upload later, went into the recordings section under the profile and uploaded from here).  Upload later was successful both times.
