### ISSUE TITLE
Touch events (dragging esp.) seem to pause the LPC

### ISSUE THREAD

**Issue by starakaj** [ByunLab/staRt-ionic#41]
Why exactly is a bit mysterious, especially since three js demo examples seem to run okay, even through touch events. It could have something to do with fetching data from the audio thread, but it bears more investigation.

**Comment by helencarey** [comment]
I thought the issue was more like: **_slider and other touch input (except for the nav) are unresponsive after page change, also LPC slows down a little_**

for me the problem includes:
- issue exists in iOS app only -- it runs fine in simulator
- present after transitioning from all pages with actual content (profiles, tutorial, words, resources), not just those w/ the LPC/those making calls to the Audio Engine
- ‘text highlight bubble thing’ often comes up on touch while app is unresponsive (maybe disabling this will help)

**Comment by helencarey** [comment]
the stuff I was going to try includes:

- 1. disable LPC draw loop but not bg processes (like setting the filter order) - see if I can isolate the prob
- 2. get a better understanding of our page load profile (what's being called in what order)
- 3. look into what touch events are being generated in ionic. kill unnecessary stuff.
- 4. look into how our sliders are working & see if the starfish slider can be optimized -- like maybe we are supposed to be using built-in ionic slider, maybe our slider is triggering unnecessary updates, etc

**do these tasks seem worthwhile/is this what i'm supposed to be doing?**

**Comment by starakaj** [comment]
Hey Helen, would you mind seeing how this feels for you now? Should be merged into Master and working alright now.

**Comment by helencarey** [comment]
SOOOOOOO smooth!!!    Next we need to check on the Byun Lab ipads b/c they had the iPads2s (single-core, ~2011 models).
