### ISSUE TITLE
Fix function declarations

### ISSUE THREAD

**Issue by WillHaack** [ByunLab/staRt-ionic#422]
Inner block functions cannot be declared with

`function functionName () { ... } `

they must be written as

`var functionName = function () {...};`

I see this error in a few places in the code, such as for should_calculate_difficulty in practice_directive. This will break the app on older versions of ios.

**Comment by jonathan-chin** [comment]
thanks. can we run a grep to identify all files and line numbers where such a thing occurs?

**Comment by WillHaack** [comment]
I'm sure it is possible, but we need to write a regex that matches a function defined with another function. Eslint I believe can catch it for us.

**Comment by helencarey** [comment]
Eslint can def check for that.

-h
iPhone


On Nov 11, 2019, at 09:14, Will Haack <notifications@github.com> wrote:

﻿

I'm sure it is possible, but we need to write a regex that matches a
function defined with another function. Eslint I believe can catch it for
us.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ByunLab_staRt-2Dionic_issues_422-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DACCABQHQJSZU7J34MGA5VC3QTFSEZA5CNFSM4JLV7BQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDW6MXY-23issuecomment-2D552461919&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=sdQYtDY9zFum7HlWmzDgZXYAbaQWQaump3RLYExAJqg&m=9ET7JIkvct5zjis7koQa8-F6MuXsGpxL5OEkmeC3WAE&s=G1m-mK5yjDsLbTwbD32S34RCgWOjERYphjvfXAh3dq4&e=>,
or unsubscribe
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACCABQAUKWG5UWWKRJJQ2YTQTFSEZANCNFSM4JLV7BQQ&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=sdQYtDY9zFum7HlWmzDgZXYAbaQWQaump3RLYExAJqg&m=9ET7JIkvct5zjis7koQa8-F6MuXsGpxL5OEkmeC3WAE&s=NQdpnu0uNXW7TOZ15Z3gyzj4ZEH5xkFbPNIOpacUd14&e=>
.

**Comment by jonathan-chin** [comment]
ahhh I can look into it

**Comment by helencarey** [comment]
'I see this error in a few places in the code'
^ @WillHaack Is this all in the practice-directive? If so, I can take care of it. I need to clean it up anyway.

**Comment by WillHaack** [comment]
@helencarey @jonathan-chin (Tagging because below is relevant to you too)

Okay that'd be great. Let's fix all the function definitions in one PR, after we have our mega-PR merged. Going forward I'd like to have PRs address one (small) task and only that small task (no format changes in diffs!) Any feature we add between now and February will have very little time to be tested, and as such we need to do our best to make sure new code is not adding any bugs. 

@helencarey 

I haven't done a thorough scan but I saw them here 

https://github.com/ByunLab/staRt-ionic/blob/f7bf89b4e4c3ec38e1033347ae8e65cc7d987ba6/staRt/www/common-components/practice-directive/practice-directive_controller.js#L164-L168

and here

https://github.com/ByunLab/staRt-ionic/blob/f7bf89b4e4c3ec38e1033347ae8e65cc7d987ba6/staRt/www/common-components/practice-directive/practice-directive_questScoring.js#L115

**Comment by helencarey** [comment]
Hey all (@jonathan-chin @WillHaack),

@jonathan-chin do you use vsCode? If so, enable this plug-in: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint.

**install**
The docs say that once the plugin is installed it should auto-detect our eslintrc. 
It did not initially auto-detect it for me, but then I did: 
- F1 (brings up cmd palette)
- search for 'Create ESLint configuration'
- it will tell you that you already have a config file, and when you go back to your code you'll start seeing the linting suggestions.

**rationale:**
The CLI method we have was fine, but we often forgot to run it. When we did the diffs on our PRs were nearly unusable due tons of formatting changes. If we all realtime-lint, PRs and debugging should get easier, repo will get tidier.... the code gods will be happier.

**Comment by jonathan-chin** [comment]
:( I'm heavily opinionated and use emacs almost exclusively

**Comment by WillHaack** [comment]
@jonathan-chin That is fine, I use emacs heavily myself and have emacs bindings set for visual studio. We will just need to make sure you have an indent setting that conforms to the ESlint standards for whatever mode you use. 

Regarding emacs - you may enjoy reading [Xah Lee's emacs blog.]( http://ergoemacs.org/emacs/emacs.html ) He has lots of tutorials both beginner and advanced on emacs, useful bits of elisp, as well as some keybindings that make emacs more ergonomic. On that note, a word of caution - the default settings of emacs on a normal keyboard have been known to [permanently damage wrists](http://ergoemacs.org/emacs/emacs_hand_pain_celebrity.html) from extensive use. Your pinky has to bend awkwardly to press the meta/ctrl key all the time. If you spend a lot of time using emacs it may be worth investing in a [good keyboard](http://ergoemacs.org/emacs/emacs_best_keyboard.html).
